'use client'

import { useMemo, useState } from 'react'
import { Dumbbell, Grid2X2, List, MoreHorizontal, Plus, Search, SlidersHorizontal, Timer, X } from 'lucide-react'

type Origin = 'Global' | 'Del gimnasio'
type Exercise = { name: string; description: string; instructions: string; muscle: string; secondary: string; equipment: string; category: string; tracking: string; origin: Origin; tone: string }

const exercises: Exercise[] = [
  { name: 'Press de banca', description: 'Empuje horizontal para desarrollar fuerza y masa en el torso.', instructions: 'Apoyá los pies, retraé las escápulas y bajá la barra con control.', muscle: 'Pecho', secondary: 'Tríceps, hombros', equipment: 'Barra', category: 'Fuerza', tracking: 'Peso + repeticiones', origin: 'Global', tone: 'purple' },
  { name: 'Sentadilla con barra', description: 'Patrón fundamental para fuerza de piernas y glúteos.', instructions: 'Mantené el torso firme y descendé hasta romper el paralelo.', muscle: 'Piernas', secondary: 'Glúteos, core', equipment: 'Barra', category: 'Fuerza', tracking: 'Peso + repeticiones', origin: 'Global', tone: 'blue' },
  { name: 'Peso muerto', description: 'Levantamiento compuesto para la cadena posterior.', instructions: 'Acercá la barra al cuerpo y extendé cadera y rodillas al mismo tiempo.', muscle: 'Espalda / cadena posterior', secondary: 'Glúteos, isquios', equipment: 'Barra', category: 'Fuerza', tracking: 'Peso + repeticiones', origin: 'Global', tone: 'orange' },
  { name: 'Plancha', description: 'Ejercicio isométrico para estabilidad y control del core.', instructions: 'Formá una línea recta y sostené la posición sin elevar la cadera.', muscle: 'Core', secondary: 'Hombros', equipment: 'Peso corporal', category: 'Estabilidad', tracking: 'Tiempo', origin: 'Global', tone: 'green' },
  { name: 'Cinta caminadora', description: 'Trabajo cardiovascular adaptable a distintos niveles.', instructions: 'Elegí una velocidad constante y mantené una postura erguida.', muscle: 'Cardio', secondary: 'Cuerpo completo', equipment: 'Cinta', category: 'Cardio', tracking: 'Tiempo + distancia', origin: 'Global', tone: 'cyan' },
  { name: 'Curl de bíceps con mancuernas', description: 'Aislamiento simple para fortalecer los flexores del codo.', instructions: 'Mantené los codos quietos y controlá la bajada.', muscle: 'Bíceps', secondary: 'Antebrazos', equipment: 'Mancuernas', category: 'Fuerza', tracking: 'Peso + repeticiones', origin: 'Del gimnasio', tone: 'pink' },
]

const filters = ['Grupo muscular', 'Equipamiento', 'Categoría', 'Tipo de seguimiento', 'Origen']

export function ExercisesLibraryModule() {
  const [query, setQuery] = useState('')
  const [origin, setOrigin] = useState<'Todos' | Origin>('Todos')
  const [view, setView] = useState<'grid' | 'list'>('grid')
  const [selected, setSelected] = useState<Exercise | null>(null)
  const [creating, setCreating] = useState(false)
  const filtered = useMemo(() => exercises.filter(exercise => (origin === 'Todos' || exercise.origin === origin) && `${exercise.name} ${exercise.muscle} ${exercise.equipment} ${exercise.category} ${exercise.tracking}`.toLowerCase().includes(query.toLowerCase())), [origin, query])

  return <div className="exercises-module">
    <div className="page-heading exercises-heading"><div><p className="eyebrow">Entrenamiento · Biblioteca</p><h1>Ejercicios</h1><p className="subtitle">Explorá y gestioná la biblioteca de ejercicios del gimnasio.</p></div><button className="primary-button" onClick={() => setCreating(true)}><Plus className="size-4" />Nuevo ejercicio</button></div>
    <div className="exercise-origin-tabs" role="tablist" aria-label="Origen de ejercicios">{(['Todos', 'Global', 'Del gimnasio'] as const).map(item => <button key={item} role="tab" aria-selected={origin === item || item === 'Todos' && origin === 'Todos'} className={(origin === item || item === 'Todos' && origin === 'Todos') ? 'is-active' : ''} onClick={() => setOrigin(item === 'Todos' ? 'Todos' : item)}>{item}<span>{item === 'Todos' ? exercises.length : exercises.filter(exercise => exercise.origin === item).length}</span></button>)}</div>
    <div className="exercise-toolbar exercise-filter-toolbar"><label className="exercise-search"><Search className="size-4" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar ejercicio..." aria-label="Buscar ejercicio" /></label><div className="exercise-filter-row">{filters.map(filter => <button className="exercise-filter" key={filter}><SlidersHorizontal className="size-3.5" />{filter}</button>)}<button className="exercise-clear" onClick={() => setQuery('')}>Limpiar filtros</button></div><div className="exercise-view-toggle" role="group" aria-label="Cambiar vista"><button className={view === 'grid' ? 'is-active' : ''} onClick={() => setView('grid')} aria-label="Vista Grid"><Grid2X2 className="size-4" /></button><button className={view === 'list' ? 'is-active' : ''} onClick={() => setView('list')} aria-label="Vista Lista"><List className="size-4" /></button></div></div>
    {filtered.length ? <div className={`exercise-cards ${view === 'list' ? 'is-list' : ''}`}>{filtered.map(exercise => <article className="exercise-card" key={exercise.name} onClick={() => setSelected(exercise)}><div className={`exercise-visual exercise-tone-${exercise.tone}`}><Dumbbell className="size-7" /><span>{exercise.origin}</span></div><div className="exercise-card-body"><div className="exercise-card-title"><div><p className="exercise-kicker">{exercise.muscle}</p><h2>{exercise.name}</h2></div><button className="exercise-more" aria-label={`Acciones para ${exercise.name}`} onClick={event => event.stopPropagation()}><MoreHorizontal className="size-4" /></button></div><div className="exercise-meta"><span>{exercise.equipment}</span><span><Timer className="size-3.5" />{exercise.tracking}</span></div><div className="exercise-card-footer"><span className={`origin-badge ${exercise.origin === 'Global' ? 'origin-global' : 'origin-gym'}`}>{exercise.origin}</span><span className="usage-copy">{exercise.category}</span></div></div></article>)}</div> : <div className="exercise-empty"><Dumbbell className="size-6" /><h2>No encontramos ejercicios.</h2><p>Probá cambiando los filtros o creá un ejercicio para tu gimnasio.</p><button className="primary-button" onClick={() => setCreating(true)}><Plus className="size-4" />Nuevo ejercicio</button></div>}
    {selected && <div className="exercise-overlay" onClick={() => setSelected(null)}><aside className="exercise-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)} aria-label="Cerrar detalle"><X className="size-4" /></button><div className={`drawer-visual exercise-tone-${selected.tone}`}><Dumbbell className="size-9" /></div><p className="eyebrow">Detalle de ejercicio</p><h2>{selected.name}</h2><p className="drawer-muted">{selected.description}</p><div className="drawer-detail-grid"><span><b>Grupo muscular</b>{selected.muscle}</span><span><b>Músculos secundarios</b>{selected.secondary}</span><span><b>Equipamiento</b>{selected.equipment}</span><span><b>Categoría</b>{selected.category}</span><span><b>Seguimiento</b>{selected.tracking}</span><span><b>Origen</b>{selected.origin}</span></div><div className="drawer-instructions"><b>Instrucciones</b><p>{selected.instructions}</p></div><button className="primary-button drawer-action">{selected.origin === 'Global' ? 'Duplicar en mi gimnasio' : 'Editar ejercicio'}</button></aside></div>}
    {creating && <div className="exercise-overlay" onClick={() => setCreating(false)}><aside className="exercise-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={() => setCreating(false)} aria-label="Cerrar nuevo ejercicio"><X className="size-4" /></button><p className="eyebrow">Biblioteca del gimnasio</p><h2>Nuevo ejercicio</h2><p className="drawer-muted">Creá una versión propia para reutilizar en tus rutinas.</p><div className="exercise-upload">Imagen del ejercicio<span>Arrastrá una imagen o elegí un placeholder</span></div><label className="drawer-field">Nombre<input placeholder="Ej: Press landmine" /></label><label className="drawer-field">Grupo muscular<select defaultValue=""><option value="" disabled>Seleccionar grupo</option><option>Pecho</option><option>Espalda</option><option>Hombros</option><option>Piernas</option><option>Core</option></select></label><label className="drawer-field">Tipo de seguimiento<select defaultValue=""><option value="" disabled>Seleccionar tipo</option><option>Peso + repeticiones</option><option>Repeticiones</option><option>Tiempo</option><option>Distancia</option><option>Tiempo + distancia</option></select></label><button className="primary-button drawer-action" onClick={() => setCreating(false)}><Plus className="size-4" />Guardar ejercicio</button></aside></div>}
  </div>
}
