'use client'

import { useMemo, useState } from 'react'
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, Copy, Dumbbell, MoreHorizontal, Plus, Search, UserRound, X } from 'lucide-react'

type Routine = { name: string; coach: string; members: number; exercises: number; duration: string; status: 'Activa' | 'Borrador' | 'Archivada'; updated: string; tone: string }

const routines: Routine[] = [
  { name: 'Fuerza · Tren superior', coach: 'Agustín García', members: 18, exercises: 7, duration: '45 min', status: 'Activa', updated: 'Actualizada hoy', tone: 'purple' },
  { name: 'Hipertrofia · Día B', coach: 'Sofía Martínez', members: 14, exercises: 8, duration: '55 min', status: 'Activa', updated: 'Actualizada ayer', tone: 'blue' },
  { name: 'Acondicionamiento base', coach: 'Agustín García', members: 9, exercises: 6, duration: '35 min', status: 'Activa', updated: 'Actualizada hace 3 días', tone: 'orange' },
  { name: 'Movilidad · Día A', coach: 'Sofía Martínez', members: 6, exercises: 5, duration: '30 min', status: 'Borrador', updated: 'Creada hace 5 días', tone: 'green' },
  { name: 'Introducción al gimnasio', coach: 'Agustín García', members: 0, exercises: 9, duration: '40 min', status: 'Archivada', updated: 'Archivada el 21/08/2026', tone: 'slate' },
]

export function RoutinesModule() {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'Todas' | Routine['status']>('Todas')
  const [selected, setSelected] = useState<Routine | null>(null)
  const [creating, setCreating] = useState(false)
  const [assigning, setAssigning] = useState<Routine | null>(null)
  const filtered = useMemo(() => routines.filter(routine => (status === 'Todas' || routine.status === status) && `${routine.name} ${routine.coach}`.toLowerCase().includes(query.toLowerCase())), [query, status])

  return <div className="routines-module">
    <div className="page-heading routines-heading"><div><p className="eyebrow">Entrenamiento · Gestión</p><h1>Rutinas</h1><p className="subtitle">Creá, revisá y asigná planes de entrenamiento para tus socios.</p></div><button className="primary-button" onClick={() => setCreating(true)}><Plus className="size-4" />Nueva rutina</button></div>
    <div className="routine-kpis"><div><span className="routine-kpi-icon"><Dumbbell /></span><p>Rutinas activas</p><strong>18</strong><small>+3 este mes</small></div><div><span className="routine-kpi-icon"><UserRound /></span><p>Socios con rutina</p><strong>126</strong><small>50,8% de socios activos</small></div><div><span className="routine-kpi-icon"><Clock3 /></span><p>Revisión pendiente</p><strong>6</strong><small>Para hoy</small></div></div>
    <div className="routine-toolbar"><label className="routine-search"><Search className="size-4" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar rutina o entrenador..." aria-label="Buscar rutina o entrenador" /></label><div className="routine-tabs" role="tablist" aria-label="Filtrar rutinas">{(['Todas', 'Activa', 'Borrador', 'Archivada'] as const).map(item => <button key={item} role="tab" aria-selected={status === item} className={status === item ? 'is-active' : ''} onClick={() => setStatus(item)}>{item}<span>{item === 'Todas' ? routines.length : routines.filter(routine => routine.status === item).length}</span></button>)}</div></div>
    <div className="routine-table-wrap"><table className="routine-table"><thead><tr><th>Rutina</th><th>Entrenador</th><th>Socios asignados</th><th>Ejercicios</th><th>Duración</th><th>Estado</th><th>Actualización</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{filtered.map(routine => <tr key={routine.name} onClick={() => setSelected(routine)}><td><div className={`routine-color routine-color-${routine.tone}`}><Dumbbell /></div><div><strong>{routine.name}</strong><small>Plan personalizado</small></div></td><td>{routine.coach}</td><td><span className="routine-members"><UserRound />{routine.members}</span></td><td>{routine.exercises}</td><td>{routine.duration}</td><td><span className={`routine-status routine-status-${routine.status.toLowerCase()}`}>{routine.status}</span></td><td className="routine-updated">{routine.updated}</td><td><button className="routine-more" aria-label={`Acciones para ${routine.name}`} onClick={event => event.stopPropagation()}><MoreHorizontal /></button></td></tr>)}</tbody></table>{!filtered.length && <div className="routine-empty"><Dumbbell /><h2>No encontramos rutinas</h2><p>Probá con otro término o creá una nueva rutina.</p><button className="primary-button" onClick={() => setCreating(true)}><Plus className="size-4" />Nueva rutina</button></div>}</div>
    <div className="routine-mobile-list">{filtered.map(routine => <article key={routine.name} className="routine-mobile-card" onClick={() => setSelected(routine)}><div className={`routine-color routine-color-${routine.tone}`}><Dumbbell /></div><div className="min-w-0 flex-1"><div className="routine-mobile-title"><h2>{routine.name}</h2><span className={`routine-status routine-status-${routine.status.toLowerCase()}`}>{routine.status}</span></div><p>{routine.coach}</p><div><span><UserRound />{routine.members} socios</span><span><Dumbbell />{routine.exercises} ejercicios</span><span><Clock3 />{routine.duration}</span></div></div><ChevronRight /></article>)}</div>
    {selected && <div className="routine-overlay" onClick={() => setSelected(null)}><aside className="routine-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)} aria-label="Cerrar detalle"><X className="size-4" /></button><div className={`routine-detail-hero routine-color-${selected.tone}`}><Dumbbell /></div><p className="eyebrow">Detalle de rutina</p><h2>{selected.name}</h2><p className="drawer-muted">Plan creado por {selected.coach}, listo para acompañar el progreso de tus socios.</p><div className="routine-detail-stats"><span><b>{selected.exercises}</b>ejercicios</span><span><b>{selected.duration}</b>duración</span><span><b>{selected.members}</b>asignados</span></div><div className="routine-detail-list"><p><Check />Calentamiento y movilidad incluidos</p><p><Check />Seguimiento de peso y repeticiones</p><p><Check />Progresión semanal sugerida</p></div><div className="routine-drawer-actions"><button className="secondary-button" onClick={() => setAssigning(selected)}><UserRound className="size-4" />Asignar a socio</button><button className="primary-button"><ArrowUpRight className="size-4" />Editar rutina</button></div></aside></div>}
    {creating && <div className="routine-overlay" onClick={() => setCreating(false)}><aside className="routine-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={() => setCreating(false)} aria-label="Cerrar nueva rutina"><X className="size-4" /></button><p className="eyebrow">Entrenamiento · Biblioteca</p><h2>Nueva rutina</h2><p className="drawer-muted">Creá la estructura base y luego agregá ejercicios.</p><label className="drawer-field">Nombre de rutina<input placeholder="Ej: Fuerza · Día A" /></label><label className="drawer-field">Entrenador responsable<select defaultValue=""><option value="" disabled>Seleccionar entrenador</option><option>Agustín García</option><option>Sofía Martínez</option></select></label><label className="drawer-field">Objetivo<select defaultValue=""><option value="" disabled>Seleccionar objetivo</option><option>Fuerza</option><option>Hipertrofia</option><option>Acondicionamiento</option><option>Movilidad</option></select></label><button className="primary-button drawer-action" onClick={() => setCreating(false)}><Plus className="size-4" />Guardar rutina</button></aside></div>}
    {assigning && <div className="routine-overlay" onClick={() => setAssigning(null)}><aside className="routine-drawer routine-assign-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={() => setAssigning(null)} aria-label="Cerrar asignación"><X className="size-4" /></button><p className="eyebrow">Asignar rutina</p><h2>{assigning.name}</h2><p className="drawer-muted">Elegí los socios que van a recibir este plan.</p><label className="drawer-field">Buscar socio<input placeholder="Ej: Luciano Romero" /></label><div className="assign-member"><span className="avatar avatar-purple">LR</span><span><b>Luciano Romero</b><small>Fuerza · Tren superior</small></span><input type="checkbox" defaultChecked aria-label="Asignar a Luciano Romero" /></div><div className="assign-member"><span className="avatar avatar-blue">MS</span><span><b>María Solís</b><small>Hipertrofia · Día B</small></span><input type="checkbox" aria-label="Asignar a María Solís" /></div><button className="primary-button drawer-action" onClick={() => setAssigning(null)}><Check className="size-4" />Confirmar asignación</button></aside></div>}
  </div>
}
