'use client'

import { useMemo, useState } from 'react'
import { Archive, ArrowLeft, ArrowUpRight, Check, ChevronRight, Copy, Dumbbell, Edit3, MoreHorizontal, Plus, Search, Users, X } from 'lucide-react'

type RoutineStatus = 'Activa' | 'Borrador' | 'Inactiva' | 'Archivada'
type AssignmentFilter = 'Todas' | 'Con socios' | 'Sin asignar'

type Routine = { name: string; objective: string; exercises: number; duration: string; members: number; updated: string; status: RoutineStatus; description: string }

const routines: Routine[] = [
  { name: 'Fuerza e hipertrofia', objective: 'Hipertrofia', exercises: 7, duration: '55 min', members: 8, updated: '03/09/2026', status: 'Activa', description: 'Plan de fuerza progresiva para mejorar volumen y rendimiento.' },
  { name: 'Full Body Inicial', objective: 'Acondicionamiento', exercises: 6, duration: '45 min', members: 12, updated: '01/09/2026', status: 'Activa', description: 'Rutina de adaptación general para comenzar a entrenar.' },
  { name: 'Piernas y glúteos', objective: 'Hipertrofia', exercises: 8, duration: '60 min', members: 5, updated: '29/08/2026', status: 'Activa', description: 'Bloque enfocado en fuerza y volumen del tren inferior.' },
  { name: 'Movilidad y Core', objective: 'Movilidad', exercises: 5, duration: '35 min', members: 4, updated: '27/08/2026', status: 'Activa', description: 'Trabajo de movilidad, control y estabilidad central.' },
  { name: 'Fuerza Base', objective: 'Fuerza', exercises: 6, duration: '50 min', members: 0, updated: '22/08/2026', status: 'Borrador', description: 'Base técnica para progresar en los principales patrones.' },
]

export function TrainerRoutinesModule({ onBack, onBuilder, onMember }: { onBack?: () => void; onBuilder: () => void; onMember: () => void }) {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'Todas' | RoutineStatus>('Todas')
  const [objective, setObjective] = useState('Todos')
  const [assignment, setAssignment] = useState<AssignmentFilter>('Todas')
  const [selected, setSelected] = useState<Routine | null>(null)
  const [showNew, setShowNew] = useState(false)
  const [showMembers, setShowMembers] = useState(false)
  const filtered = useMemo(() => routines.filter(r => (!query || r.name.toLowerCase().includes(query.toLowerCase())) && (status === 'Todas' || r.status === status) && (objective === 'Todos' || r.objective === objective) && (assignment === 'Todas' || (assignment === 'Con socios' ? r.members > 0 : r.members === 0))), [query, status, objective, assignment])
  return <div className="trainer-routines-page">
    <div className="trainer-routines-heading">{onBack && <button className="trainer-back-link" onClick={onBack}><ArrowLeft /> Rutinas</button>}<div><p className="eyebrow">Vista de coaching</p><h1>Mis rutinas</h1><p className="subtitle">Creá, organizá y asigná rutinas a tus socios.</p></div><button className="primary-button" onClick={() => setShowNew(true)}><Plus /> Nueva rutina</button></div>
    <div className="trainer-routine-kpis"><Kpi label="Rutinas activas" value="12" icon={Dumbbell} /><Kpi label="Socios con rutina" value="38" icon={Users} /><Kpi label="Sin rutina" value="6" icon={ArrowUpRight} /></div>
    <section className="trainer-routines-toolbar"><label className="trainer-routine-search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar rutina..." /></label><select aria-label="Estado" value={status} onChange={e => setStatus(e.target.value as typeof status)}><option>Todas</option><option>Activa</option><option>Borrador</option><option>Inactiva</option><option>Archivada</option></select><select aria-label="Objetivo" value={objective} onChange={e => setObjective(e.target.value)}><option>Todos</option><option>Hipertrofia</option><option>Fuerza</option><option>Movilidad</option><option>Acondicionamiento</option></select><select aria-label="Asignación" value={assignment} onChange={e => setAssignment(e.target.value as AssignmentFilter)}><option>Todas</option><option>Con socios</option><option>Sin asignar</option></select><button className="clear-filters" onClick={() => { setQuery(''); setStatus('Todas'); setObjective('Todos'); setAssignment('Todas') }}>Limpiar filtros</button></section>
    {filtered.length ? <div className="trainer-routine-grid">{filtered.map(routine => <article className="trainer-routine-card" key={routine.name}><div className="trainer-routine-card-top"><div className="trainer-routine-icon"><Dumbbell /></div><button className="icon-button" aria-label={`Acciones de ${routine.name}`}><MoreHorizontal /></button></div><div className="trainer-routine-card-heading"><div><h2>{routine.name}</h2><p>{routine.objective}</p></div><StatusBadge status={routine.status} /></div><div className="trainer-routine-meta"><span>{routine.exercises} ejercicios</span><span>{routine.duration}</span></div><div className="trainer-routine-assigned"><Users /><button onClick={() => routine.members ? setShowMembers(true) : undefined}>{routine.members ? `${routine.members} socios` : 'Sin asignar'}</button><small>Actualizada {routine.updated}</small></div><div className="trainer-routine-card-actions"><button className="secondary-button" onClick={() => setSelected(routine)}>Ver</button>{routine.status !== 'Archivada' && <button className="text-link" onClick={onBuilder}>{routine.status === 'Borrador' ? 'Continuar editando' : 'Editar'} <Edit3 /></button>}</div><button className="routine-assign-cta" onClick={() => routine.members ? setShowMembers(true) : undefined}>{routine.members ? 'Asignar' : 'Asignar socios'} <ChevronRight /></button></article>)}</div> : <div className="trainer-routines-empty"><h2>No encontramos rutinas.</h2><p>Probá cambiando los filtros.</p><button className="secondary-button" onClick={() => { setQuery(''); setStatus('Todas'); setObjective('Todos'); setAssignment('Todas') }}>Limpiar filtros</button></div>}
    {selected && <div className="trainer-routine-overlay" onClick={() => setSelected(null)}><aside className="trainer-routine-drawer" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}><X /></button><p className="eyebrow">Detalle de rutina</p><h2>{selected.name}</h2><StatusBadge status={selected.status} /><p className="drawer-description">{selected.description}</p><div className="drawer-summary"><span><strong>{selected.objective}</strong>Objetivo</span><span><strong>{selected.exercises}</strong>Ejercicios</span><span><strong>{selected.duration}</strong>Duración</span></div><h3>Ejercicios preview</h3>{['Press de banca · 4 × 10','Remo con barra · 4 × 10','Sentadilla · 4 × 8'].map(item => <div className="drawer-exercise" key={item}><Dumbbell />{item}</div>)}<div className="drawer-actions"><button className="secondary-button" onClick={onBuilder}><Edit3 /> Editar rutina</button><button className="primary-button" onClick={() => setShowMembers(true)}><Users /> Asignar a socio</button></div></aside></div>}
    {showMembers && <div className="trainer-routine-overlay" onClick={() => setShowMembers(false)}><aside className="trainer-routine-drawer small" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setShowMembers(false)}><X /></button><p className="eyebrow">Socios asignados</p><h2>Socios de la rutina</h2>{['Juan Pérez','María González','Tomás Acosta'].map(name => <button className="assigned-member" key={name} onClick={onMember}><span className="avatar avatar-purple">{name.split(' ').map(n => n[0]).join('')}</span><span>{name}</span><ChevronRight /></button>)}</aside></div>}
    {showNew && <div className="trainer-routine-overlay" onClick={() => setShowNew(false)}><div className="trainer-new-routine" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setShowNew(false)}><X /></button><p className="eyebrow">Nueva rutina</p><h2>Empezá una nueva plantilla</h2><label>Nombre<input placeholder="Ej. Fuerza e hipertrofia" /></label><label>Objetivo<select><option>Hipertrofia</option><option>Fuerza</option><option>Movilidad</option></select></label><label>Descripción<textarea placeholder="Contale a tu equipo para qué sirve esta rutina." /></label><button className="primary-button" onClick={onBuilder}>Continuar al constructor <ArrowUpRight /></button></div></div>}
  </div>
}
function Kpi({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Users }) { return <div className="trainer-routine-kpi"><span><Icon /></span><div><p>{label}</p><strong>{value}</strong></div></div> }
function StatusBadge({ status }: { status: RoutineStatus }) { return <span className={`routine-status routine-status-${status.toLowerCase()}`}>{status}</span> }
export default TrainerRoutinesModule
