'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowUpRight, BarChart3, CalendarCheck2, Check, ChevronRight, Dumbbell, MoreHorizontal, Pencil, Plus, TrendingUp } from 'lucide-react'

type Tab = 'Resumen' | 'Entrenamiento' | 'Progreso' | 'Actividad'

const week = [['Lunes', true], ['Martes', false], ['Miércoles', true], ['Jueves', false], ['Viernes', true]] as const
const exercises = [['Press de banca', '50 kg × 10', '47,5 kg × 10', '↑'], ['Sentadilla', '70 kg × 8', '70 kg × 8', '—'], ['Remo con barra', '45 kg × 10', '42,5 kg × 10', '↑']] as const

export function TrainerMemberDetail({ onBack }: { onBack: () => void }) {
  const [tab, setTab] = useState<Tab>('Resumen')
  return <div className="trainer-detail">
    <button className="trainer-detail-back" onClick={onBack}><ArrowLeft /> Mis socios</button>
    <header className="trainer-detail-header">
      <div className="trainer-detail-identity"><div className="member-avatar member-avatar-large">JP</div><div><p className="eyebrow">Mis socios / Juan Pérez</p><h1>Juan Pérez</h1><p className="trainer-detail-contact">juan.perez@email.com</p><p className="trainer-detail-meta">Entrena desde marzo 2026 · Entrenador: Luciano Romero</p></div></div>
      <div className="trainer-detail-actions"><span className="trainer-active-badge">Activo</span><button className="secondary-button"><Pencil /> Editar rutina</button><button className="primary-button"><Plus /> Asignar rutina</button><button className="icon-button" aria-label="Más acciones"><MoreHorizontal /></button></div>
    </header>
    <div className="trainer-detail-stats"><TrainerStat label="Rutina actual" value="Fuerza e hipertrofia" detail="4 días · 7 ejercicios" icon={Dumbbell} /><TrainerStat label="Último entrenamiento" value="Hoy · 08:42" detail="Sesión completada" icon={CalendarCheck2} /><TrainerStat label="Progreso semanal" value="3 de 4 sesiones" detail="Esta semana" icon={BarChart3} /><TrainerStat label="Streak" value="4 semanas" detail="Consistencia semanal" icon={TrendingUp} /></div>
    <div className="trainer-detail-tabs" role="tablist" aria-label="Detalle del socio">{(['Resumen', 'Entrenamiento', 'Progreso', 'Actividad'] as Tab[]).map(item => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? 'trainer-detail-tab-active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'Resumen' ? <div className="trainer-detail-grid"><main className="trainer-detail-main">
      <section className="trainer-detail-card trainer-routine-card"><div className="trainer-card-heading"><div><p className="eyebrow">Rutina actual</p><h2>Fuerza e hipertrofia</h2></div><span className="trainer-routine-status">Activa</span></div><div className="trainer-routine-meta"><span>Objetivo <strong>Hipertrofia</strong></span><span>4 días</span><span>7 ejercicios</span><span>55 min</span></div><p className="trainer-card-muted">Inicio: 25/08/2026</p><div className="trainer-inline-actions"><button className="secondary-button">Ver rutina <ChevronRight /></button><button className="text-link">Editar asignación <Pencil /></button></div></section>
      <section className="trainer-detail-card"><div className="trainer-card-heading"><div><p className="eyebrow">Cumplimiento reciente</p><h2>Sesiones de la semana</h2></div><span className="trainer-week-total">3 de 4</span></div><div className="trainer-week-list">{week.map(([day, done]) => <div key={day}><span>{done ? <Check /> : '—'}</span><strong>{day}</strong><small>{done ? 'Completado' : 'Pendiente'}</small></div>)}</div><p className="trainer-card-muted">3 de 4 entrenamientos completados esta semana</p></section>
      <section className="trainer-detail-card"><div className="trainer-card-heading"><div><p className="eyebrow">Progreso reciente</p><h2>Cómo viene entrenando</h2></div><button className="text-link">Ver progreso <ArrowUpRight /></button></div><div className="trainer-progress-grid"><div><strong>+8%</strong><span>Volumen entrenado · último mes</span></div><div><strong>11</strong><span>Sesiones completadas · este mes</span></div><div><strong>82%</strong><span>Consistencia</span></div></div></section>
      <section className="trainer-detail-card"><div className="trainer-card-heading"><div><p className="eyebrow">Rendimiento</p><h2>Últimos ejercicios</h2></div></div><div className="trainer-exercise-list">{exercises.map(([name, latest, previous, trend]) => <div key={name}><div><strong>{name}</strong><small>Último: {latest} · Anterior: {previous}</small></div><span className={trend === '↑' ? 'trainer-trend-up' : ''}>{trend}</span></div>)}</div></section>
    </main><aside className="trainer-detail-side"><section className="trainer-detail-card"><div className="trainer-card-heading"><div><p className="eyebrow">Constancia</p><h2>4 semanas</h2></div><span className="streak-mini-mark">↗</span></div><p className="trainer-card-muted">Cumplimiento semanal, no días consecutivos.</p><div className="trainer-streak-days">{['L','M','X','J','V','S','D'].map((day, i) => <span key={day} className={i < 5 ? 'is-done' : ''}>{i < 5 ? <Check /> : day}</span>)}</div></section><section className="trainer-detail-card"><div className="trainer-card-heading"><div><p className="eyebrow">Actividad reciente</p><h2>Últimos movimientos</h2></div></div><div className="trainer-timeline">{[['Hoy · 08:42','Completó entrenamiento','Fuerza e hipertrofia'],['03/09 · 18:10','Completó entrenamiento',''],['01/09 · 08:35','Completó entrenamiento',''],['29/08','Rutina asignada','']].map(([time, title, detail]) => <div key={time}><span /><div><small>{time}</small><strong>{title}</strong>{detail && <p>{detail}</p>}</div></div>)}</div></section><section className="trainer-detail-card trainer-attention"><p className="eyebrow">Atención</p><h2>Le queda 1 sesión</h2><p>para completar su objetivo semanal.</p></section></aside></div> : <div className="trainer-detail-placeholder"><p className="eyebrow">{tab}</p><h2>{tab === 'Entrenamiento' ? 'Rutina e historial de workouts' : tab === 'Progreso' ? 'Tendencias de progreso' : 'Actividad de entrenamiento'}</h2><p>Este espacio queda preparado para consultar la información de {tab.toLowerCase()} sin mezclar datos administrativos.</p></div>}
  </div>
}

function TrainerStat({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Dumbbell }) { return <article className="trainer-detail-stat"><span><Icon /></span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }

export default TrainerMemberDetail
